[package]
name = "bevy-dino"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = "0.16.1"
bevy_aspect_ratio_mask = "0.2.0"
bevy_asset_loader = { version = "0.23.0", features = ["2d"] }
bevy_common_assets = { version = "0.13", features = ["json"] }
rand = "0.9.2"
serde = "1.0.219"
